name: Build
on:
  release:
    types: [published]
  pull_request: null
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build executable
      run: ./do.sh build
    - name: Archive executable
      uses: actions/upload-artifact@v4
      with:
        name: ElytraChestplates
        path: build/*.zip
