name: Build
on:
  release:
    types: [published]
  pull_request: null
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@v16
      with:
        # Commit corresponds to tag v0.30.0 and installs nix v2.24.0.
        source-revision: b4bc792f575248e63e92c95cd9d334d01ba86b71
        # Disable telemetry.
        diagnostic-endpoint: ""
    - name: Setup cache
      uses: DeterminateSystems/magic-nix-cache-action@v8
      with:
        # Commit corresponds to tag v0.1.3.
        source-revision: fbf0bbed9401ae4069096a6025bb624f20cd4f4c
        # Disable telemetry.
        diagnostic-endpoint: ""
    - name: Check flake
      uses: DeterminateSystems/flake-checker-action@v9
      with:
        # Commit corresponds to tag v0.2.0.
        source-revision: 6ba8ec538e8b959957932c3416ea9384b7cef170
        # Disable telemetry.
        send-statistics: false
        ignore-missing-flake-lock: false
        fail-mode: true
    - name: Build
      run: nix run .
    - name: Archive executable
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ElytraChestplates
        path: .build/*.zip
