name: Lint
on:
  release:
    types: [published]
  pull_request: null
  workflow_dispatch: null
jobs:
  shell:
    runs-on: ubuntu-24.04
    container: koalaman/shellcheck-alpine:v0.10.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint
      run: shellcheck do.sh
  json:
    runs-on: ubuntu-24.04
    container: alpine:3.20.3
    steps:
    - name: Install dependencies
      run: apk update && apk add --no-cache jq=1.7.1-r0
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint
      run: cat datapack/pack.mcmeta | jq type 1>/dev/null
