name: Lint
on:
  release:
    types: [published]
  pull_request: null
  workflow_dispatch: null
jobs:
  shell:
    runs-on: ubuntu-24.04
    container: koalaman/shellcheck-alpine:v0.10.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint
      run: shellcheck do.sh
  json:
    runs-on: ubuntu-24.04
    container: ghcr.io/jqlang/jq:1.7.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint
      run: cat datapack/pack.mcmeta | jq type 1>/dev/null
